<?php

/**
 * BD CONST
 */
const HOST="localhost";
const USER="root";
const PASS="icaballero23";
const DATABASE="cisadnetwork";
  

/**
 * IDS CONST
 */
//Login
const BACK=1;
const LOGOUT=10;
const AUTHENTICATION=100;

//USER
const USERPANEL=101;
const USERMODIFY=102;
const SAVEMODIFYUSER=103;
const USERDELETED=104;
const CONFUSERDELETED=105;

//Movies
const BACKMOVIES=2;
const MOVIESPANEL=106;
const MOVIESMODIFY=107;
const ACTORSMOVIE=108;
const DELMOVIEACTOR=109;
const ADDACTORMOVIE=110;
const DIRECTORSMOVIES=111;
const ADDDIRECTORMOVIES=112;
const DELDIRECTORMOVIES=113;
const SAVEMODIFYMOVIE=114;
const DELMOVIES=116;
const CONFDELETEMOVIES=117;

//Series
const BACKSERIES=3;
const SERIESPANEL=115;
const MODIFYSERIES=118;
const CONFDELETESERIES=119;
const DELETESERIE=120;
const SAVEMODIFYSERIE=121;
const ACTORSERIES=122;
const ADDACTORSERIE=123;
const DELSERIEACTOR=124;
const DIRECTORSERIES=125;
const ADDDIRECTORSERIES=126;
const DELDIRECTORSERIE=127;
const DELCHAPTERSERIE=128;
const ADDNEWCHAPTER=129;
const CONFNEWCHAPTER=130;


//Cookrecide
const BACKCOOKRECIDE=4;
const COOKSPANEL=131;
const MODIFYCOOKS=132;
const SAVEMODIFYCOOKS=133;
const CONFDELETECOOKS=134;
const DELETECOOKS=135;


//Books
const BACKBOOKS=5;
const BOOKSPANEL=136;
const MODIFYBOOKS=137;
const SAVEMODIFYBOOKS=138;
const CONFDELBOOKS=139;
const DELBOOKS=140;








?>